#!/bin/bash

capitalize() {
  echo "$1" | awk '{ print toupper(substr($0,1,1)) tolower(substr($0,2)) }'
}

name=$(jq -r '.name' pokemon.json | capitalize)
height=$(jq -r '.height' pokemon.json)
weight=$(jq -r '.weight' pokemon.json)
type=$(jq -r '.types[0].type.name' pokemon.json | capitalize)

formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")
formatted_weight=$(awk "BEGIN {printf \"%d\", $weight / 10}")

echo "${name} is of type ${type}, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
